### PR TITLE
Automatic packaging and releasing of an eSim version for Ubuntu OS

### PR DESCRIPTION
**Pull request by saicharan0112**
### Related Issues

https://github.com/FOSSEE/eSim/issues/211

### Purpose

To pack and release the eSim for Ubuntu automatically, whenever a tag which starts with "v" is pushed to the GitHub

### Approach

The workflow follows the instructions given under the Ubuntu section of the installer branch and uses GitHub Actions (GHA) to build and release the package automatically when the relevant tag is created and pushed to the GitHub. See the action with name "Auto release of eSim for Ubuntu OS" for more details on the workflow.

Note: This can be replicated for OS too.

### CODE REVIEW

**Comment by saicharan0112** [comment]
@Eyantra698Sumanto This should do address the issue #211

**Comment by saicharan0112** [comment]
@rahulp13 @Eyantra698Sumanto Did you both had a chance to review the PR? If I could get some feedback/suggestions, I can implement them today.

**Comment by Eyantra698Sumanto** [comment]
@saicharan0112 Thanks for the PR. We will soon look into it and get back to you.

**Comment by saicharan0112** [comment]
Sure, thanks @Eyantra698Sumanto

**Pull request merged**
